### ISSUE TITLE
10xwhitelist.txt not included

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [BUStools/Notebooks#2]
This file is referenced in the R notebook but not included in the repo

**Comment by lambdamoses** [comment]
Here is where you can get the 10xwhitelist file: https://kb.10xgenomics.com/hc/en-us/articles/115004506263-What-is-a-barcode-whitelist-
You don't have to run Cell Ranger to get it, but you do need to install Cell Ranger; it's a file that comes with Cell Ranger, with a list of all known barcodes included in the 10x assay kit.
