### ISSUE TITLE
Error when creating `res_mat`

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [BUStools/Notebooks#3]
When I get to the step in the notebook to create `res_mat`

`res_mat <- fill_cell_geneR("output.sort.txt", ECs$genes, whitelist = whitelist, est_ncells = 7e5, est_ngenes = 8e4)`

I get the following error: 

`Error in (function (cl, name, valueClass) : assignment of an object of class “numeric” is not valid for @‘Dim’ in an object of class “dgTMatrix”; is(value, "integer") is not TRUE`

I am using the output from `kallisto bus` run on Chromium 1k human/mouse data that has been sorted and exported to text format. 

`> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.1 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] loomR_0.2.0         itertools_0.1-3     iterators_1.0.10    hdf5r_1.0.1         R6_2.3.0            Seurat_2.3.4       
 [7] cowplot_0.9.3       ggplot2_3.1.0       Rcpp_1.0.0          zeallot_0.1.0       stringr_1.3.1       Biostrings_2.50.1  
[13] XVector_0.22.0      IRanges_2.16.0      S4Vectors_0.20.1    BiocGenerics_0.28.0 Matrix_1.2-15       data.table_1.11.8  `

**Comment by lambdamoses** [comment]
Inside the `sparseMatrix` function, the `i` (from `rowind`) and `j` (calculated from `rowind` and `colptr`) are explicitly converted into integer, and the dimensions of the matrix are from the maximum of `i` and `j`, so should in principle be integers, so your problem is quite mysterious. I'm unable to reproduce your problem in my system. To solve the problem once and for all, I'll make the C++ function directly return a sparse matrix from `RcppArmadillo`, so types can't be messed up. I'll push the updated notebook and the C++ function shortly.

**Comment by lambdamoses** [comment]
OK, I have changed the code to bypass the `sparseMatrix` call that caused your problem. Please download the updated notebook and C++ file and let me know if there're problems.

**Comment by JasonJWilliamsNY** [comment]
Thanks for checking so quickly (I hope to teach with this in a few days). I now get a new error when I am loading the libraries: 

`Error: Package 'RcppArmadillo' referenced from Rcpp::depends in source file fill_cell_gene.cpp is not available.`

I am running this on an RStudio server session, so I could give access for you to look and reproduce (off thread)

**Comment by lambdamoses** [comment]
You should install RcppArmadillo; it's a separate package from Rcpp

**Comment by JasonJWilliamsNY** [comment]
Thanks - I misread the documentation and thought it was part of Rccp. This works now, however it seems like I am not getting the matrix. Object `res_mat` is created but seems empty:

`[1] "2018-11-30 23:48:47 UTC"
Reading data
Constructing sparse matrix
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|

[1] "2018-11-30 23:48:48 UTC"
`

I am assuming the 1.5G sorted bus text file is in the right format:

`$ head output_sorted.txt`
AAAAAAAAAAAAAAAA        AAAAAAAAAA      246173  1
AAAAAAAAAAAAAAAA        AAAAAAAAAA      1076301 1
AAAAAAAAAAAAAAAA        AAAAGAACCA      553619  1
AAAAAAAAAAAAAAAA        ATAAAAAAAA      321346  1
AAAAAAAAAAAAAAAA        ATAACCAAAA      1207183 1
AAAAAAAAAAAAAAAA        CCCTGGTATC      456094  1
AAAAAAAAAAAAAAAC        TAAACAAAAC      313279  1
AAAAAAAAAAAAAACA        AAAACACATC      451008  1
AAAAAAAAAAAAAATA        ATCAAACAAA      523919  1
AAAAAAAAAAAAAGTC        AAGAGGAAAT      513903  1


The next two test cells of the notebook return TRUE, but `summary(tot_umi)` has no stats.

**Comment by lambdamoses** [comment]
Yes, the file you're referring to is correct. What you're describing looks like you're supplying the wrong file name or path; the matrix is empty when that file doesn't exist. I added a check for the existence of the file in the `fill_cell_geneR` function in the notebook; somehow that check did not work. Please change the path pointing to `output_sorted.txt` to the path relative to the notebook. RStudio sets the working directory of code from within code chunks in R notebooks as the directory where the notebook itself is in, rather than the directory of the R project.

If that still doesn't work, then can I take a look at your server session? It worked fine on my server.

**Comment by lambdamoses** [comment]
It only took 1 second to read in the "file", which happens when the file name or path supplied to `fn` is incorrect. On my server, it took 5 to 6 minutes to read in an approximately 10GB file (the hgmm6k dataset), so I would expect it to take at least half a minute to read in your file.

**Comment by JasonJWilliamsNY** [comment]
I am able to create `res_mat`!

`>str(res_mat)

 Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
   ..@ i       : int [1:12515659] 0 1 2 3 4 5 6 7 8 9 ...
   ..@ p       : int [1:284125] 0 2 3 9 10 11 12 14 15 34 ...
   ..@ Dim     : int [1:2] 44590 284124
   ..@ Dimnames:List of 2
   .. ..$ : chr [1:44590] "ENSG00000220583.1" "ENSG00000136942.14" "ENSMUSG00000093674.7"     "ENSG00000231502.6" ...
   .. ..$ : chr [1:284124] "TTTGTCATCTTTACAC" "TTTGTCATCTTGTCAT" "TTTGTCATCTTGCATT"  "TTTGTCATCTTGAGAC" ...
   ..@ x       : num [1:12515659] 0.5 0.5 1 0.167 0.167 ...
   ..@ factors : list()`

Everything else in the notebook goes smoothly until I try to normalize the loom object that is created. As written when I try the normalize function I get

`NormalizeData(hgmm1k, chunk.size = NULL, chunk.dims = NULL)
Error in NormalizeData(hgmm1k, chunk.size = NULL, chunk.dims = NULL) : 
  unused arguments (chunk.size = NULL, chunk.dims = NULL)`

If I remove those NULL arguments I get:
`> NormalizeData(hgmm1k)
Error in SetCalcParams(object = object, calculation = "NormalizeData",  : 
  trying to get slot "calc.params" from an object (class "loom") that is not an S4 object `

Not sure if this is a new issue. I notice I cannot view `res_mat`; I get the error:

`>View(res_mat)
Error in if (more || nchar(output) > 80) { : 
  missing value where TRUE/FALSE needed`

**Comment by pmelsted** [comment]
Seurat has a branch that supports loom files, you need to have that branch installed to work with loom files. 

Add this to the top and things should work from there
`devtools::install_github(repo = "satijalab/seurat", ref = "loom")`

**Comment by lambdamoses** [comment]
You don't have to follow the notebook all the way. The only reason why I used the loom branch of Seurat is that I used the large hgmm6k dataset. You can modify the notebook to use the in memory version of Seurat. The loom feature will not be included in the 3.0 release of Seurat. I'll edit the notebook to avoid such confusions.

**Comment by lambdamoses** [comment]
I just clarified that the loom branch of Seurat should be used, and added another section in the notebook using the in memory version of Seurat, so please download the new version of the notebook. Sorry for the confusion. Thank you for your feedback!
