### ISSUE TITLE
collapsing BUS into TCC

### ISSUE THREAD

**Issue by coh-racng** [BUStools/Notebooks#5]
I want to collapse BUS data into TCC for differential analysis method shown in 
Ntranos, Yi et al., 2019. 
I have modified the code from BUS notebooks for generating `cell_gene` dictionary to make an analogous `cell_ec` dictionary. For each umi, I incremented each equivalence classes by its count divided the sum of all counts for that umi. Should I instead increment each equivalence class matched for a particular umi with equal weight (ex. 1/len(eclist))?
Do you have suggestions for collapsing BUS into TCC?

**Comment by vasilisNt** [comment]
Thank you for asking! We currently have an example **bus to tcc** notebook available here: https://github.com/BUStools/BUS_notebooks_python/blob/master/dataset-notebooks/10x_t4k_TCC/bus2tcc-gene.ipynb
Although we use the t4k dataset as an example, the notebook is general so you should be able to use it without any major modifications; it takes the sorted bus file as input together with the tx to gene and gene to name dictionaries generated from get_dicts-from-ref.ipynb (available in the utils folder: https://github.com/BUStools/BUS_notebooks_python/blob/master/utils/) and outputs both the TCC and the corresponding Gene Count matrices.

**Comment by coh-racng** [comment]
slicing the ENST caused problems in downstream analysis when the ENST has double digits for version number. For example, ENST00000348564.11 (transcript for CD45 RO) became 'ENST00000348564.' with an extra period. 
``` Python
# load transcripts        
trlist = []
with open(busdir+'transcripts.txt') as f:
    for line in f:
        trlist.append(line[:-3])
```

Should replace with ` trlist.append(line.split('.')[0])`
